title: Rediscovering the clinical pharmacist within
email: not-a-real-email(at)really-not-providing(dot)com
description: >-
  This is to document my learning around oncology and blogging in markdown.



# Build Settings
theme: minima